### ISSUE TITLE
Video Camera Recording issue

### ISSUE THREAD

**Issue by HeshamMorsy** [Mindinventory/Lassi-Android#94]
Hello all,

I have an application on google play store and it uses camera recording by lassi library, but The clients have an issue on Samsung Galaxy Tab A7 (android version : 12).

When I try to record a video on the back camera (default one) the camera just previewed the first frame when I opened the camera and freezes.
I can't record a video on back camera, but the selfi-camera (front one) works fine.

Logs :
`D/Camera: app passed NULL surface
`

Please help me if there is any solution for this critical bug .

This is the code I open the camera with :

 
```
 val options = if (hideGallery) LassiOption.CAMERA else LassiOption.CAMERA_AND_GALLERY
       
 val intent = Lassi(requireContext())
            .with(options) // choose Option CAMERA, GALLERY or CAMERA_AND_GALLERY
            .setMaxCount(1)
            .setGridSize(3)
            .setMediaType(MediaType.VIDEO) // MediaType : VIDEO IMAGE, AUDIO OR DOC
            .setCompressionRation(10) // compress image for single item selection (can be 0 to 100)
            .setMinTime(1) // for MediaType.VIDEO only
            .setMaxTime(1 * 60) // for MediaTyp e.VIDEO only
            .setSupportedFileTypes(
                "mp4",
                "mkv",
                "webm",
                "avi",
                "flv",
                "mov",
                "3gp",
            ) // Filter by limited media format (Optional)
            .setMinFileSize(100) // Restrict by minimum file size
            .setMaxFileSize(10 * 1024L * 1024L) //  Restrict by maximum file size
            .disableCrop() // to remove crop from the single image selection (crop is enabled by default for single image)
            /*
             * Configuration for  UI
             */
            .setStatusBarColor(R.color.black)
            .setProgressBarColor(R.color.reverseAppBackground)
            .setPlaceHolder(com.lassi.R.drawable.ic_image_placeholder)
            .setErrorDrawable(com.lassi.R.drawable.ic_image_placeholder)
            .setSelectionDrawable(R.drawable.fi_check)
            .setGalleryBackgroundColor(R.color.appBackground)//Customize background color of gallery (default color is white)
            .build()
       
 receiveData.launch(intent)
```

Thank you

Update :

When I click on record the timer is shown and counting, and when I stop it nothing happens and the log printed is as following :

```
E/Camera: Error 1
E/Camera1: Internal Camera1 error. 1
E/AndroidRuntime: FATAL EXCEPTION: CameraViewController
    Process: com.cilium.dev, PID: 27611
    com.lassi.presentation.cameraview.controls.CameraException: java.lang.RuntimeException: Internal Camera1 error. 1
        at com.lassi.presentation.cameraview.controls.Camera1.onError(Camera1.java:407)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1214)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.RuntimeException: Internal Camera1 error. 1
        at com.lassi.presentation.cameraview.controls.Camera1.onError(Camera1.java:395)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1214) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:226) 
        at android.os.Looper.loop(Looper.java:313) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
E/CameraController: uncaughtException: Interrupting thread with state: STATE_STARTED due to CameraException: com.lassi.presentation.cameraview.controls.CameraException: java.lang.RuntimeException: Internal Camera1 error. 1
    com.lassi.presentation.cameraview.controls.CameraException: java.lang.RuntimeException: Internal Camera1 error. 1
        at com.lassi.presentation.cameraview.controls.Camera1.onError(Camera1.java:407)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1214)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.RuntimeException: Internal Camera1 error. 1
        at com.lassi.presentation.cameraview.controls.Camera1.onError(Camera1.java:395)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1214) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:226) 
        at android.os.Looper.loop(Looper.java:313) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
D/Camera: app passed NULL surface
E/Camera1: unbindFromSurface Could not release surface java.io.IOException: setPreviewTexture failed
    java.io.IOException: setPreviewTexture failed
        at android.hardware.Camera.setPreviewTexture(Native Method)
        at com.lassi.presentation.cameraview.controls.Camera1.unbindFromSurface(Camera1.java:218)
        at com.lassi.presentation.cameraview.controls.Camera1.onStop(Camera1.java:345)
        at com.lassi.presentation.cameraview.controls.CameraController.stopImmediately(CameraController.java:225)
        at com.lassi.presentation.cameraview.controls.CameraController$2.run(CameraController.java:145)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.os.HandlerThread.run(HandlerThread.java:67)

```

And after investigating I found that camera error 1 related to that another app is using camera and it's not true, there isn't any opened app. 
Library version : 1.1.0

**Comment by sanjay-mi** [comment]
Hello @HeshamMorsy 

Thank you for using the Lassi Library.

I have tried to regenerate your scenario with a Samsung mobile device and Lassi version 1.2.0 but not able to reproduce it. It's working fine for me.
Please try to check with the Lassi sample and use the latest Lassi version 1.2.0. 

Thank you
